// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-x6lx2xo-OLCLuxGYh2u9ucRp8wrdsrI',
    appId: '1:69917520956:web:6e99bcc1f9b9f042d17f39',
    messagingSenderId: '69917520956',
    projectId: 'loginfirebase-81244',
    authDomain: 'loginfirebase-81244.firebaseapp.com',
    storageBucket: 'loginfirebase-81244.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-aZ3Q5Qgz7yBavLcJ4EwgB0bR6a_9gFE',
    appId: '1:69917520956:android:5591e138adc29d40d17f39',
    messagingSenderId: '69917520956',
    projectId: 'loginfirebase-81244',
    storageBucket: 'loginfirebase-81244.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCQ6X4RjZbZhNgryZ9hmPplpG05IidriI',
    appId: '1:69917520956:ios:d5b5d14870046885d17f39',
    messagingSenderId: '69917520956',
    projectId: 'loginfirebase-81244',
    storageBucket: 'loginfirebase-81244.appspot.com',
    iosBundleId: 'com.example.testproject1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCQ6X4RjZbZhNgryZ9hmPplpG05IidriI',
    appId: '1:69917520956:ios:e957855cd89b3241d17f39',
    messagingSenderId: '69917520956',
    projectId: 'loginfirebase-81244',
    storageBucket: 'loginfirebase-81244.appspot.com',
    iosBundleId: 'com.example.testproject1.RunnerTests',
  );
}
